# Python tips to HELP YOU

In [1]:
import numpy as np

In [12]:
foo = np.random.randint(30, size=(20))
print (foo)
print ('Shape:', foo.shape)

[ 0 16  5  0 10  7 10  8 16 28 21 16  9  2 10  0 10  2  9 17]
Shape: (20,)


## Boolean indexing

how about indexing a NUMPY ARRAY with a NUMPY ARRAY OF BOOLEANS

Heck Yeah!

In [4]:
foo

array([17, 13,  5, 10, 25,  7,  9, 27, 25, 26, 27, 13,  8, 27,  5,  3, 17,
       13, 14,  3])

In [5]:
foo > 15

array([ True, False, False, False,  True, False, False,  True,  True,
        True,  True, False, False,  True, False, False,  True, False,
       False, False], dtype=bool)

In [8]:
# Get the values from foo that are greater than 15
bool_mask = foo > 15
foo[ bool_mask ]

array([17, 25, 27, 25, 26, 27, 27, 17])

In [11]:
# You can use this mask on any ol' array of the same size

labels = np.random.choice(['hat', 'whale', 'trebuchet', 'burt'], size=len(foo))
print (labels)
print ('Shape:', labels.shape)
print (labels[ bool_mask ] )


['burt' 'hat' 'burt' 'trebuchet' 'trebuchet' 'whale' 'hat' 'hat'
 'trebuchet' 'trebuchet' 'whale' 'trebuchet' 'burt' 'whale' 'burt'
 'trebuchet' 'hat' 'trebuchet' 'hat' 'trebuchet']
Shape: (20,)
['burt' 'trebuchet' 'hat' 'trebuchet' 'trebuchet' 'whale' 'whale' 'hat']


## 2D arrays

Syntax: [row_slice, column_slice]

In [17]:
bar = np.random.randint(100, size=(8, 6))
print ('Shape:', bar.shape)

Shape: (8, 6)


In [21]:
print("bar (whole array)\n ", bar)
print("bar[2] (2nd line, zero indexed)\n ", bar[2])
print("bar[3,4] (number in 3rd row fourth col)\n ", bar[3,4])
print("bar[2:5,:-2] (rows 2 through 5, and columns up to two from the end)\n ", bar[2:5,:-2])
print("bar[-1:2:-1] (from the last row to the second, in reverse order)\n ", bar[-1:2:-1])
print("bar[2,::2] (second row, every other column)\n ", bar[2,::2])
print("bar[-1] (the last row)\n ", bar[-1])

bar (whole array)
  [[18 11  7 60 65 99]
 [29 89 34 32 48 19]
 [31 30 52 83 91 21]
 [13 91  6 36 39 81]
 [60 36 48  3 63 11]
 [10 56 21 13 71 35]
 [33 81 17 59 98  8]
 [66 21 92 46 78  5]]
bar[2] (2nd line, zero indexed)
  [31 30 52 83 91 21]
bar[3,4] (number in 3rd row fourth col)
  39
bar[2:5,:-2] (rows 2 through 5, and columns up to two from the end)
  [[31 30 52 83]
 [13 91  6 36]
 [60 36 48  3]]
bar[-1:2:-1] (from the last row to the second, in reverse order)
  [[66 21 92 46 78  5]
 [33 81 17 59 98  8]
 [10 56 21 13 71 35]
 [60 36 48  3 63 11]
 [13 91  6 36 39 81]]
bar[2,::2] (second row, every other column)
  [31 52 91]
bar[-1] (the last row)
  [66 21 92 46 78  5]


## Boolean masks with 2D arrays

In [45]:
print("original array: \n", bar)
print("original array: \n", bar > 20)
print("values greater than 20: \n", bar[ bar > 20 ])
print("average of values greater than 20: \n", (bar > 20).mean())
print("average of values greater than 20, by column: \n", (bar > 20).mean(axis=0))
print("average of values greater than 20, by row: \n", (bar > 20).mean(axis=1))
print("values in the third column greater than 40: \n ", bar[:, 3] > 40)
print("selecting rows where the third column value is greater than 40: \n ", bar[bar[:, 3] > 40])
mask3 = bar[3, :] > 40
print("mask3 (mask3 = bar[3, :] > 40)\n ", mask3)
print("bar[:,mask3] \n", bar[:,mask3])

original array: 
 [[18 11  7 60 65 99]
 [29 89 34 32 48 19]
 [31 30 52 83 91 21]
 [13 91  6 36 39 81]
 [60 36 48  3 63 11]
 [10 56 21 13 71 35]
 [33 81 17 59 98  8]
 [66 21 92 46 78  5]]
original array: 
 [[False False False  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]
 [False  True False  True  True  True]
 [ True  True  True False  True False]
 [False  True  True False  True  True]
 [ True  True False  True  True False]
 [ True  True  True  True  True False]]
values greater than 20: 
 [60 65 99 29 89 34 32 48 31 30 52 83 91 21 91 36 39 81 60 36 48 63 56 21 71
 35 33 81 59 98 66 21 92 46 78]
average of values greater than 20: 
 0.729166666667
average of values greater than 20, by column: 
 [ 0.625  0.875  0.625  0.75   1.     0.5  ]
average of values greater than 20, by row: 
 [ 0.5         0.83333333  1.          0.66666667  0.66666667  0.66666667
  0.66666667  0.83333333]
values in the third column greater than 40: 
  [ True False 

In [53]:
# How about the rows that contain at least one value greater than 70?

mask1 = (bar > 70)
print("mask1 \n ", mask1)
print("mask1.any(axis=0)\n ", mask1.any(axis=0))
print("mask1.any(axis=1)\n ", mask1.any(axis=0))
print("bar[mask1.any(axis=1)]\n ", mask1.any(axis=0))

# also mask1.all?

mask1 
  [[False False False False False  True]
 [False  True False False False False]
 [False False False  True  True False]
 [False  True False False False  True]
 [False False False False False False]
 [False False False False  True False]
 [False  True False False  True False]
 [False False  True False  True False]]
mask1.any(axis=0)
  [False  True  True  True  True  True]
mask1.any(axis=1)
  [False  True  True  True  True  True]
bar[mask1.any(axis=1)]
  [False  True  True  True  True  True]


## Indexing an array with a list

In [57]:
print("foo\n ",foo)
list_mask1 = [1, 6, 4, 2]
print("foo[list_mask1]\n ",foo[list_mask1])
list_mask2 = [4, 4, 4, 4]
print("foo[list_mask2]\n ",foo[list_mask2])
print("bar[list_mask1]\n ",bar[list_mask1])
print("bar[list_mask2]\n ",bar[list_mask2])
print("bar[:,list_mask2]\n ",bar[:,list_mask2])

foo
  [ 0 16  5  0 10  7 10  8 16 28 21 16  9  2 10  0 10  2  9 17]
foo[list_mask1]
  [16 10 10  5]
foo[list_mask2]
  [10 10 10 10]
bar[list_mask1]
  [[29 89 34 32 48 19]
 [33 81 17 59 98  8]
 [60 36 48  3 63 11]
 [31 30 52 83 91 21]]
bar[list_mask2]
  [[60 36 48  3 63 11]
 [60 36 48  3 63 11]
 [60 36 48  3 63 11]
 [60 36 48  3 63 11]]
bar[:,list_mask2]
  [[65 65 65 65]
 [48 48 48 48]
 [91 91 91 91]
 [39 39 39 39]
 [63 63 63 63]
 [71 71 71 71]
 [98 98 98 98]
 [78 78 78 78]]


## Smushing arrays together¶


In [58]:
x1 = np.random.randint(1240,8754,size=(20,1))
x2 = np.random.random(size=(20,1))

In [60]:
print("x1\n ",x1)
print("x2\n ",x2)
print("np.concatenate((x1, x2), axis=1)\n ",np.concatenate((x1, x2), axis=1))
print("np.concatenate((x1, x2), axis=0)\n ",np.concatenate((x1, x2), axis=0))
print("np.hstack((x1, x2))\n ",np.hstack((x1, x2)))
print("np.vstack((x1, x2))\n ",np.vstack((x1, x2)))
print("np.hstack((x1, x2))\n ",np.hstack((x1, x2)))

x1
  [[6557]
 [5345]
 [2467]
 [8363]
 [6833]
 [4699]
 [3842]
 [2231]
 [8128]
 [5169]
 [3762]
 [4242]
 [6482]
 [3827]
 [2051]
 [2157]
 [1749]
 [7121]
 [7050]
 [5990]]
x2
  [[ 0.94708154]
 [ 0.54403034]
 [ 0.53424141]
 [ 0.98631078]
 [ 0.60376462]
 [ 0.68940426]
 [ 0.23837084]
 [ 0.45204409]
 [ 0.76721112]
 [ 0.75875202]
 [ 0.27212794]
 [ 0.16347486]
 [ 0.35350932]
 [ 0.19329675]
 [ 0.8240933 ]
 [ 0.43253086]
 [ 0.05133189]
 [ 0.2802773 ]
 [ 0.08955921]
 [ 0.33395465]]
np.concatenate((x1, x2), axis=1)
  [[  6.55700000e+03   9.47081535e-01]
 [  5.34500000e+03   5.44030340e-01]
 [  2.46700000e+03   5.34241410e-01]
 [  8.36300000e+03   9.86310777e-01]
 [  6.83300000e+03   6.03764617e-01]
 [  4.69900000e+03   6.89404255e-01]
 [  3.84200000e+03   2.38370839e-01]
 [  2.23100000e+03   4.52044093e-01]
 [  8.12800000e+03   7.67211117e-01]
 [  5.16900000e+03   7.58752021e-01]
 [  3.76200000e+03   2.72127942e-01]
 [  4.24200000e+03   1.63474856e-01]
 [  6.48200000e+03   3.53509316e-01]
 [  3.827000

In [ ]:
x3 = np.random.randint(-50, -2, size=20)
x3
x3.shape
np.hstack((x1, x2, x3))
np.hstack((x1, x2, x3.reshape(-1,1)))
x3.reshape(-1,1)
bar.reshape(-1,1)

## True is 1, False is 0

In [61]:
bar > 50

array([[False, False, False,  True,  True,  True],
       [False,  True, False, False, False, False],
       [False, False,  True,  True,  True, False],
       [False,  True, False, False, False,  True],
       [ True, False, False, False,  True, False],
       [False,  True, False, False,  True, False],
       [False,  True, False,  True,  True, False],
       [ True, False,  True, False,  True, False]], dtype=bool)

In [62]:
type(_)

numpy.ndarray

In [63]:
(bar > 50).sum()

19

In [64]:
(bar > 50).mean()

0.39583333333333331

## Oh the booleanity!

In [73]:
print("bool(5): ",bool(5))
print("bool(0): ",bool(0))
print("bool('banananas'): ",bool('banananas'))
print("bool(''): ",bool(''))
print("bool(None): ",bool(None))
print("True == bool(6): ",True == bool(6))
print("False == None: ",False == None)
print("0 == False: ",0 == False)
print("bool(np.nan): ",bool(np.nan))
print("np.nan == True: ",np.nan == True)
print("np.nan == np.nan: ",np.nan == np.nan)
print("bool(np.inf): ",bool(np.inf))
print("np.inf == np.inf: ",np.inf == np.inf)
print("bool([3, '', 32]): ",bool([3, '', 32]))
print("bool([]): ",bool([]))
print("bool(['']): ",bool(['']))
print("None == None: ",None == None)
print("np.bool_: ",np.bool_)

bool(5):  True
bool(0):  False
bool('banananas'):  True
bool(''):  False
bool(None):  False
True == bool(6):  True
False == None:  False
0 == False:  True
bool(np.nan):  True
np.nan == True:  False
np.nan == np.nan:  False
bool(np.inf):  True
np.inf == np.inf:  True
bool([3, '', 32]):  True
bool([]):  False
bool(['']):  True
None == None:  True
np.bool_:  <class 'numpy.bool_'>
